CREATE TABLE navigations (
	id INT(11) NOT NULL AUTO_INCREMENT,
	title VARCHAR(255),
	output TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)