CREATE TABLE galleries (
	id INT(11) NOT NULL AUTO_INCREMENT,
	title VARCHAR(255),
	description VARCHAR(255),
	page_id int,
	slides TEXT,
	active TINYINT(1),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (page_id) REFERENCES Pages(id)
)