CREATE TABLE pages (
	id INT(11) NOT NULL AUTO_INCREMENT,
	page VARCHAR(255),
	title VARCHAR(255),
	subtitle VARCHAR(255),
	description LONGTEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)