CREATE TABLE cart_items (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product varchar(255) NOT NULL,
  cart_id int(11) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cart_id) REFERENCES carts(id)
)